### ISSUE TITLE
[FEATURE] 建议提供预编译构件 (Native-Image)

### ISSUE THREAD

**Issue by iceBear67** [Ghost-chu/PeerBanHelper#1]
我简单翻了一下代码，发现没有用到太多的反射特性，于是挂个 tracing agent 本地跑了一下构建

感觉编译通过的希望还是很大的

![image](https://github.com/Ghost-chu/PeerBanHelper/assets/48877375/79bb1cca-caab-46a8-85f8-7db27c82b501)

不清楚是不是 graal 的问题，但是到连接的时候爆炸了。如果能 AOT 的话，可以进一步压缩资源占用并且提供更快的冷启动速度

当然，这只是一个建议，不是说非要不可（

Full log: https://angry.im/paste/3K2rIDp

**Comment by Ghost-chu** [comment]
Unirest 里面是包的 Apache HttpClient。  
之前也试过用 GraalVM 编译带 Unirest 的 Native Image，都是直接爆掉，但是我看里面也没有什么黑魔法，这个就很奇怪。

**Comment by Ghost-chu** [comment]
🤔主要是 Unirest 那个 Cookies 管理方便一些，它自己就能处理好了。如果不用那个 Cookies 管理，也可以不用 Unirest 的。

**Comment by Ghost-chu** [comment]
> Author

对，qBittorrent 来说鉴权是基于 Session 的，要用到 Cookies，如果是基于 Token 大概就没这么多事情了，Java 自己的就够用了。

**Comment by iceBear67** [comment]
https://docs.oracle.com/javase/8/docs/api/java/net/CookieManager.html

我记得 Java 的那个 Modern HTTP 也可以直接给 CookieManager 来着，记得不知道什么时候用过

**Comment by iceBear67** [comment]
https://docs.oracle.com/en%2Fjava%2Fjavase%2F11%2Fdocs%2Fapi%2F%2F/java.net.http/java/net/http/HttpClient.Builder.html#cookieHandler(java.net.CookieHandler)

是这个

**Comment by Ghost-chu** [comment]
后面看看吧，也弄了不止一次这个 GraalVM 过，光架工具链就令人头皮发麻。Windows 下面环境就没配成过，唯一一次构建成功还是在 WSL 里折腾的。

**Comment by Ghost-chu** [comment]
![image](https://github.com/Ghost-chu/PeerBanHelper/assets/30802565/37a54cd9-5b36-4267-8b9f-c13e2777e739)

折腾了一天，暂时能跑起来，但是网络请求（Unirest）似乎存在严重问题，看了2个小时没有定位出原因，先睡了。  

NativeImage 工程在 https://github.com/Ghost-chu/PeerBanHelper/tree/test 上进行，构建输出在 Github Actions 里。

**Comment by Ghost-chu** [comment]
晚点看看有没有必要换成新版 Java 自带的 HttpClient

**Comment by Ghost-chu** [comment]
![image](https://github.com/Ghost-chu/PeerBanHelper/assets/30802565/a2575358-6b01-40f1-b12b-523a67bb6c00)

看起来不错

**Comment by Ghost-chu** [comment]
在 2.2-RC1 中可用：  
https://github.com/Ghost-chu/PeerBanHelper/releases/tag/2.2-RC1

**Comment by iceBear67** [comment]
好也
