### ISSUE TITLE
自簽HTTPS無法連接

### ISSUE THREAD

**Issue by MononeV** [Ghost-chu/PeerBanHelper#17]
`登录到 qbittorrent-001 失败：N/A - javax.net.ssl.SSLHandshakeException: 
PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target `

**Comment by Ghost-chu** [comment]
添加了一个新的 `verify-ssl` 的下载器配置项，允许对 qBittorrent 禁用 SSL 证书验证：https://github.com/Ghost-chu/PeerBanHelper/actions/runs/8533268716
