### ISSUE TITLE
UTF-8 兼容问题

### ISSUE THREAD

**Issue by Mishasama** [Ghost-chu/PeerBanHelper#21]
# 除了锁定编码，还得锁定能正常显示中文的字体才行哦～

![image](https://github.com/Ghost-chu/PeerBanHelper/assets/54498172/41fe9f1d-87ed-41f6-bd22-6037f1cae337)

虽然只要自己手动修改一次就可以了……但如果作为便携版使用的话则会因为配置信息丢失而使用默认值，导致再次出现无法显示中文字符的问题。搞搞它！

**Comment by Ghost-chu** [comment]
遗憾的是cmd目前不能通过自动化方式修改控制台字体（至少我没找到），大部分中文版Windows应该都是开箱即用的。

GUI和WebUI已经提上日程了，可以关注一下。

<img width="914" alt="Image_1712459966349" src="https://github.com/Ghost-chu/PeerBanHelper/assets/30802565/1bf052ba-618b-4757-8218-142f76cc794a">
<img width="809" alt="Image_1712459968579" src="https://github.com/Ghost-chu/PeerBanHelper/assets/30802565/60215abe-5372-4e46-839e-c41832a5c65e">

**Comment by Mishasama** [comment]
遗憾，我用的就是最新的懒人版……
===================

> 据说可以通过 C++ 来调用 Windows API 的 [`SetCurrentConsoleFontEx`](https://learn.microsoft.com/zh-cn/windows/console/setcurrentconsolefontex) 来达到目的。

另外据我自己的了解，只要对某一路径的程序启动的 CMD 窗口修改过属性，它就会在注册表上留下永久的信息。下次再次通过同样路径的程序打开的 CMD 窗口会复用该设置，属于一劳永逸。
也许可以考虑在启动时检查当前窗口所用的字体是否为指定的字体，如否，则尝试调用管理员权限写入注册表信息来修改字体，接着再启动（或重启？）本体。
大概……能方便一些小白或懒狗用户吧😂

举个栗子
```
:: 设置字体名称
set FontName=NSimsun

:: 获取当前字体设置
for /f "tokens=*" %%a in ('reg query "HKEY_CURRENT_USER\Console\%当前运行路径%_peerbanhelper-binary.exe" /v FaceName ^| find /i "FaceName"') do set CurrentFont=%%a

:: 判断
if CurrentFont=FontName
……
```
后面的你懂的……

**Comment by Ghost-chu** [comment]
对注册表操作远远超过了 PBH 该做的事情。作为一个小工具操作系统级注册表实在是有些越界了。  
Java 确实可以调用 C++ API，但相当麻烦。我和群友测试下没有出现字体问题，因此没有计划对此单独修正（除非有更多的人出现相同问题）。可以考虑通过日志文件查看控制台日志，或者WebUI获取信息。

**Comment by Mishasama** [comment]
其实…… CLI 直接纯英文输出不就没这事了吗😂

不过无所谓了，都有 UI 了就不考虑看 CLI 了🙄

**Comment by Ghost-chu** [comment]
实验性在 v2.7 中进行了修复，效果未知。

**Comment by Mishasama** [comment]
> 实验性在 v2.7 中进行了修复，效果未知。

![image](https://github.com/Ghost-chu/PeerBanHelper/assets/54498172/48cb280c-38dc-4591-9b8f-79e8c3ae8c70)
不知道是否跟系统对非 Unicode 程序启用了 UTF-8 支持的原因，实测依旧。
