### ISSUE TITLE
增加开关豁免私有种子

### ISSUE THREAD

**Issue by Gaojianli** [Ghost-chu/PeerBanHelper#22]
对于Private的种子类型来说，吸血行为由PT站本身来管理，希望增加开关对于Private种子进行豁免避免误伤

**Comment by Ghost-chu** [comment]
对于 qBittorrent 来说，检查种子类型需要对每个种子多增加一次请求。如果有 100 个活跃种子，那么就会额外发送 100 次请求，这会显著增加下载器的对 WebAPI 响应引起的负载。  

暂且不论负载性能问题，单从问题表明来听就非常冲突。如果 PT 站对吸血行为管理恰当，那么吸血客户端也不会触发 PBH 的反吸血规则。  
就算是玩 PT 的也是用的正常的 BT 客户端，其行为也是正常行为，不会出现反常现象。如果一个 BT 客户端出现反常现象，那只能说它完全不遵守 Bittorrent BEP 规范——而这类客户端也通常是各个 PT 站所封禁的对象。PBH 所做的工作与 PT 没有冲突的情况。恰恰相反，PBH 更有利于 PT 站的用户抓到那些在 PT 站里使用作弊工具的吸血者。

对于此提议，我决定搁置，直至有更有说服力的理由出现。

**Comment by Gaojianli** [comment]
> 对于 qBittorrent 来说，检查种子类型需要对每个种子多增加一次请求。如果有 100 个活跃种子，那么就会额外发送 100 次请求，这会显著增加下载器的对 WebAPI 响应引起的负载。
> 
> 暂且不论负载性能问题，单从问题表面来听就非常冲突。如果 PT 站对吸血行为管理恰当，那么吸血客户端也不会触发 PBH 的反吸血规则。 就算是玩 PT 的也是用的正常的 BT 客户端，其行为也是正常行为，不会出现反常现象。如果一个 BT 客户端出现反常现象，那只能说它完全不遵守 Bittorrent BEP 规范——而这类客户端也通常是各个 PT 站所封禁的对象。PBH 所做的工作与 PT 没有冲突的情况。恰恰相反，PBH 更有利于 PT 站的用户抓到那些在 PT 站里使用作弊工具的吸血者。
> 
> 对于此提议，我决定搁置，直至有更有说服力的理由出现。

对于1，种子类型可以采用缓存，并不需要每次都请求100次，对于2，我认为有道理

**Comment by n-ine** [comment]
> 对于 qBittorrent 来说，检查种子类型需要对每个种子多增加一次请求。如果有 100 个活跃种子，那么就会额外发送 100 次请求，这会显著增加下载器的对 WebAPI 响应引起的负载。
> 
> 暂且不论负载性能问题，单从问题表面来听就非常冲突。如果 PT 站对吸血行为管理恰当，那么吸血客户端也不会触发 PBH 的反吸血规则。 就算是玩 PT 的也是用的正常的 BT 客户端，其行为也是正常行为，不会出现反常现象。如果一个 BT 客户端出现反常现象，那只能说它完全不遵守 Bittorrent BEP 规范——而这类客户端也通常是各个 PT 站所封禁的对象。PBH 所做的工作与 PT 没有冲突的情况。恰恰相反，PBH 更有利于 PT 站的用户抓到那些在 PT 站里使用作弊工具的吸血者。
> 
> 对于此提议，我决定搁置，直至有更有说服力的理由出现。

对于某些客户端伪装成为tr293 294 277我都是直接ban peer id 这样 很容易错失本来该给他人的上传 而且今天早上我发现了一起TR4.0.5不汇报进度的私有种子下载 我觉得很奇怪就将其从封禁名单移除 发现对方进度80% 不管是BUG还是如何我都不想错失任何给PT的上传量 所以我请求加上此功能

**Comment by Ghost-chu** [comment]
> > 对于 qBittorrent 来说，检查种子类型需要对每个种子多增加一次请求。如果有 100 个活跃种子，那么就会额外发送 100 次请求，这会显著增加下载器的对 WebAPI 响应引起的负载。
> > 
> > 暂且不论负载性能问题，单从问题表面来听就非常冲突。如果 PT 站对吸血行为管理恰当，那么吸血客户端也不会触发 PBH 的反吸血规则。 就算是玩 PT 的也是用的正常的 BT 客户端，其行为也是正常行为，不会出现反常现象。如果一个 BT 客户端出现反常现象，那只能说它完全不遵守 Bittorrent BEP 规范——而这类客户端也通常是各个 PT 站所封禁的对象。PBH 所做的工作与 PT 没有冲突的情况。恰恰相反，PBH 更有利于 PT 站的用户抓到那些在 PT 站里使用作弊工具的吸血者。
> > 
> > 对于此提议，我决定搁置，直至有更有说服力的理由出现。
> 
> 对于某些客户端伪装成为tr293 294 277我都是直接ban peer id 这样 很容易错失本来该给他人的上传 而且今天早上我发现了一起TR4.0.5不汇报进度的私有种子下载 我觉得很奇怪就将其从封禁名单移除 发现对方进度80% 不管是BUG还是如何我都不想错失任何给PT的上传量 所以我请求加上此功能

不建议BTPT混用下载器。PT的反吸血由Tracker控制，无需PBH干涉。
可预见的未来不考虑添加此功能。
