### ISSUE TITLE
[转发] 疑似新改名客户端hp/torrent/v2.01

### ISSUE THREAD

**Issue by poplar-at-twilight** [Ghost-chu/PeerBanHelper#31]
详见：https://github.com/Simple-Tracker/qBittorrent-ClientBlocker/issues/53

我今天也遇到了这些 peer

**Comment by poplar-at-twilight** [comment]
目前我是通过 peer-blacklist.txt 暂时屏蔽这些 peer

- `-HP0001- hp/torrent/v2.01`

**Comment by Ghost-chu** [comment]
感谢汇报，确认是 dt/torrent 改名。观测到相同CIDR和种子任务下出现此Peer。

**Comment by yuyuwuyou** [comment]
> 目前我是通过 peer-blacklist.txt 暂时屏蔽这些 peer
> 
> 我的系统开机时间大约是 3 天，但 qb（qb 与 win 同步开机启动）上载量达到了 111GB，估计被这些 peer 吸走了 50GB
> 
> * `-HP0001- hp/torrent/v2.01`

用了这个规则没效果，重启客户端后依然吸血能力很强

**Comment by poplar-at-twilight** [comment]
> PBH 有触发异常上传/错误进度的自动封禁吗

我搜索了一下日志，并没有检索到拦截 `hp/torrent/v2.01` 的日志记录，这个客户端可能是最近一两天新出现的翻版。

**Comment by Radium-bit** [comment]
我也遇到了，半天吸走50GB的流量.可用的拦截表达式
-HP\d{3}- hp/torrent/v[\d.]+

**Comment by hanxuyuan** [comment]
我今天也遇到了这个客户端，刚看到还挺奇怪的

**Comment by Radium-bit** [comment]
新增的三个Peer
offline-download (devel) (anacrolix/torrent unknown)
gobind (devel) (anacrolix/torrent unknown)
go.torrent dev 20181121

**Comment by yujiangqaq** [comment]
遇到相同的恶意客户端，因为没有及时更新版本被刷了150G
IP段：
1.180.24.*
1.180.25.*
鉴于攻击者获取IP的成本较高，且过去三个月攻击者采用相同IP段仅仅通过反复更换peer ID，谎报下载进度的方式就绕过了一堆反吸血检测，是否考虑将常见的恶意IP段直接列入IP黑名单

**Comment by poplar-at-twilight** [comment]
屏蔽器的更新速度赶不上这群吸血鬼改 peer-ID 的速度，直接禁止 IP 段会更直接一些

> 2024年04月11日出现客户端为 offline-download (devel) (anacrolix/torrent unknown) 的恶意对等体，IP 地址段为 240e:90e:2000::/48。
> https://github.com/anacrolix/torrent/discussions/891#discussioncomment-8810897

> 最近又发现了两个新的吸血客户端：
> -GT0003- gobind (devel) (anacrolix/torrent unknown)
> -GT0003- offline-download (devel) (anacrolix/torrent unknown)
> 我已经考虑用Peer白名单了
> https://github.com/anacrolix/torrent/discussions/891#discussioncomment-9107245

**Comment by fangdangboy** [comment]
近期我的上传量起码被刷了500G，看这几个IP有点异常，于是拿着peer id查了一下，果然不正常
![微信图片_20240525163421](https://github.com/PBH-BTN/PeerBanHelper/assets/60640922/2fdd1123-97ea-4f78-b764-6a48cc729617)
