### ISSUE TITLE
针对服务器提出几种可以潜在发现可疑ip的方法

### ISSUE THREAD

**Issue by BUnipendix** [Ghost-chu/PeerBanHelper#33]
本人不会java，也不太了解bittorrent协议的细节，就简单说一下我的设想
**1. 一般可疑ip会成群出现**![image](https://github.com/Ghost-chu/PeerBanHelper/assets/100204822/9f45c1e0-12c8-4d06-9dce-9d4330349f5a)
他们会拥有部分相同的ip字段

**2.ping和tcp扫描确定是否为服务器**
由于使用的是机房的服务器，可以通过ping猜测ip地址是否为公网ip（一般用户nat4 ping不通，ipv6防火墙默认开启），然后扫描tcp端口确定此ip是否向外界提供大量服务
![image](https://github.com/Ghost-chu/PeerBanHelper/assets/100204822/c5a5739a-42bc-4ecb-9c16-75614876db8a)
![image](https://github.com/Ghost-chu/PeerBanHelper/assets/100204822/2ea847b7-5a2c-458a-a4fa-4f48f8825731)
其它诸如客户端诱饵（在上传一部分内容后断开连接并通过一个伪装成需要下载的客户端请求之前的ip请求之前已经上传的内容，确定对方是否为吸血客户端）之类的想法比较难以实现，暂时不考虑

**Comment by Ghost-chu** [comment]
感谢建议！

1)  
目前 v3 开发分支已支持对 IP 段自动封禁的功能
<img width="1275" alt="b6f3b15abb771ea82103053868fe9530" src="https://github.com/Ghost-chu/PeerBanHelper/assets/30802565/25d4b687-e3eb-4414-be9f-f0739a427517">

2)  
扫描行为需要大量连接，对于 BT 这种大连接数的应用来说，再加上扫描非常容易干爆路由/交换机的连接表，并导致断网。不推荐这样识别。  

3)  
客户端诱饵，不建议这样做。客户端异常退出或者校验失败也会导致已上传的片段丢失。这种情况还算比较常见。

**Comment by Gaojianli** [comment]
> 感谢建议！
> 
> 
> 目前 v3 开发分支已支持对 IP 段自动封禁的功能 <img alt="b6f3b15abb771ea82103053868fe9530" width="1275" src="https://private-user-images.githubusercontent.com/30802565/321210273-25d4b687-e3eb-4414-be9f-f0739a427517.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NTY5OTAsIm5iZiI6MTcxMjc1NjY5MCwicGF0aCI6Ii8zMDgwMjU2NS8zMjEyMTAyNzMtMjVkNGI2ODctZTNlYi00NDE0LWJlOWYtZjA3MzlhNDI3NTE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDEzNDQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1MzY5MGI4N2FkMTdiZjQ5MThmYTBlZWY4ZmY1NTJiOWVmMDRkNDU2MTU2ZmM1MTM5ODliOTY3YzIxY2EwY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Zo2C2kKTqiG2j57nX3gKsryZM5LLeCvFai2H3eMvTWY">
> 
> 
> 扫描行为需要大量连接，对于 BT 这种大连接数的应用来说，再加上扫描非常容易干爆路由/交换机的连接表，并导致断网。不推荐这样识别。
> 
> 
> 客户端诱饵，不建议这样做。客户端异常退出或者校验失败也会导致已上传的片段丢失。这种情况还算比较常见。

关于3，能否通过上传垃圾数据来判断？正经BT客户端会校验数据正确性，但是黑洞不会
