### ISSUE TITLE
Naitive Image Error: bundle inet.ipaddr.IPAddressResources is missing

### ISSUE THREAD

**Issue by Ovler-Young** [Ghost-chu/PeerBanHelper#38]
使用ip地址/端口封禁后naitive image 会出现如下告示，jar的不存在问题，但似乎并不影响CIDR ban客户端的效果
```
bundle inet.ipaddr.IPAddressResources is missing
```
![使用naitive image](https://github.com/Ghost-chu/PeerBanHelper/assets/44089074/45ca37d2-e20b-48db-bbbe-872da1d2321a)
![不使用naitive image](https://github.com/Ghost-chu/PeerBanHelper/assets/44089074/6fa442da-718d-42d2-b0ad-00b66d382085)

**Comment by Ghost-chu** [comment]
inet.ipaddr.IPAddressResources 是本地化语言文件，丢失应该没有影响

**Comment by Ghost-chu** [comment]
看看 2.8 还有这个问题吗

**Comment by Ovler-Young** [comment]
2.8解决了
