### ISSUE TITLE
[BUG] docker-compose无法运行

### ISSUE THREAD

**Issue by cloudwindy** [Ghost-chu/PeerBanHelper#4]
挂载路径`config.yml`和`profile.yml`变成文件夹，无法正常写入

**Comment by cloudwindy** [comment]
参见：moby/moby#22857

**Comment by cloudwindy** [comment]
可能的改进方案：
* 提供默认配置文件以便用户手动配置
* 检测到空文件时写入默认配置
* 将容器的导出文件放在目录内，而不是挂载为文件

**Comment by Ghost-chu** [comment]
需要预先创建文件再启动，不能让它自己创建的

**Comment by Ghost-chu** [comment]
后面考虑都挪到一个文件夹里，在改完之前先手动创建吧

**Comment by cloudwindy** [comment]
@Ghost-chu 预先创建文件后无法启动，会报空文件错误

**Comment by Ghost-chu** [comment]
> @Ghost-chu 预先创建文件后无法启动，会报空文件错误

😂肯定是要配置好的呀。

> 将提前准备好的 config.yml, profile.yml 文件上传到此文件夹中。

**Comment by jerrita** [comment]
唔，大概意思可能是，宿主机没配环境生成初始配置比较麻烦，比较好的解决方案是挂空文件上去，程序在启动前判断一下，如果是空文件就给初始文件写上再退出让自行配置会比较好。（咱不会 java 就不提 pr 了www

**Comment by Ghost-chu** [comment]
> 唔，大概意思可能是，宿主机没配环境生成初始配置比较麻烦，比较好的解决方案是挂空文件上去，程序在启动前判断一下，如果是空文件就给初始文件写上再退出让自行配置会比较好。（咱不会 java 就不提 pr 了www

是会自己生成的，但是如果已经有文件了，哪怕是空的也不会重复生成。这个后面肯定会考虑的，不方便配的话，可以从 https://github.com/Ghost-chu/PeerBanHelper/tree/master/src/main/resources 下载改完再上传就行

**Comment by jerrita** [comment]
是这样，因为用 docker-compose 只能挂载存在的文件，比较好的方案应该是挂个目录到 /config 下（x

**Comment by Ghost-chu** [comment]
2.0应该解决了这个问题，杂七杂八的文件都挪进 data 目录底下了
