### ISSUE TITLE
为什么新版本会在启动时访问互联网？

### ISSUE THREAD

**Issue by Mishasama** [Ghost-chu/PeerBanHelper#45]
防火墙报警了，请问用途是什么？

**Comment by bai0012** [comment]
> 防火墙报警了，请问用途是什么？

估计是webui吧，webui如果侦听了0.0.0.0确实会触发防火墙，但是127.0.0.1不太清楚，可能与系统设置有关

**Comment by Ghost-chu** [comment]
> > 防火墙报警了，请问用途是什么？
> 
> 估计是webui吧，webui如果侦听了0.0.0.0确实会触发防火墙，但是127.0.0.1不太清楚，可能与系统设置有关

默认监听本地127.0.0.1，现在还没有互联网请求。

**Comment by Mishasama** [comment]
> 请上传防火墙截图。

似乎是旧版的主动探测并没有正常工作，现在才正式动起来向 peer 主动发起连接，所以就触发防火墙了。

话说 WebUI 怎么进？完全都没有说明啊……😕

**Comment by Ghost-chu** [comment]
> 话说 WebUI 怎么进？完全都没有说明啊……

config.yml 下面有个 http 那个 HTTPD 服务器即负责给 Transmission 提供 blocklist，也负责 WebUI。
