### ISSUE TITLE
[Feature] 请求实现后台运行。

### ISSUE THREAD

**Issue by Radium-bit** [Ghost-chu/PeerBanHelper#49]
目前的程序会创建一个命令窗口，请求增加特性，使其通过后台无窗口化运行，或可选退到托盘内。

**Comment by poplar-at-twilight** [comment]
可以新建一个名为 `HideRun-peerbanhelper.vbs` 纯文本文件

```
CreateObject("WScript.Shell").Run "peerbanhelper-binary.exe",0
```

然后将脚本的快捷方式复制到 `shell:startup` 就可以实现开机启动

**Comment by zhongfly** [comment]
> 退到托盘

推荐试试这个，https://github.com/benbuck/rbtray 这个双击运行后，右键窗口的“最小化”，就会把窗口最小化到托盘

**Comment by Ghost-chu** [comment]
经测试，技术限制，无法实现。

**Comment by cherinyy** [comment]
> 经测试，技术限制，无法实现。

请问目前 GUI 也无法实现最小化到托盘吗？

比如“双击托盘图标实现显示或隐藏窗口”。

**Comment by Ghost-chu** [comment]
> > 经测试，技术限制，无法实现。
> 
> 请问目前 GUI 也无法实现最小化到托盘吗？
> 
> 比如“双击托盘图标实现显示或隐藏窗口”。

点击最小化按钮最小化到任务栏，点击关闭按钮最小化到系统托盘，点击托盘图标重新显示窗口，右键托盘图标/菜单可以退出。
