### ISSUE TITLE
疑似新的或伪装的吸血客户端

### ISSUE THREAD

**Issue by rihalvnium76** [Ghost-chu/PeerBanHelper#51]
```
[2024/04/14 12:44:21] [WARNING] [封禁] PeerAddress(ip=220.88.111.208, address=220.88.111.208, port=57951), PeerId=-UT360W-, ClientName=uTorrent 3.6.0.32, Progress=0.0, Uploaded=263437312, Downloaded=0, Torrent=***, Reason=客户端进度：0.00%，实际进度：0.15%，差值：0.15%
```

不定期根据日志手动补充IP封禁库时发现的

**Comment by Ghost-chu** [comment]
2.9 还是 2.8 版本

2.9 之前的版本有误报问题（如果peer断开后重新握手，可能出现webui提供的数据里有数据但数据不完整的情况）

**Comment by rihalvnium76** [comment]
> 2.9 还是 2.8 版本
> 
> 2.9 之前的版本有误报问题（如果peer断开后重新握手，可能出现webui提供的数据里有数据但数据不完整的情况）
> 
> 2.9 加了个过滤器给过滤掉了

2.8

**Comment by Ghost-chu** [comment]
> > 2.9 还是 2.8 版本
> > 2.9 之前的版本有误报问题（如果peer断开后重新握手，可能出现webui提供的数据里有数据但数据不完整的情况）
> > 2.9 加了个过滤器给过滤掉了
> 
> 2.8

是 docker 部署吗？

**Comment by rihalvnium76** [comment]
> > > 2.9 还是 2.8 版本
> > > 2.9 之前的版本有误报问题（如果peer断开后重新握手，可能出现webui提供的数据里有数据但数据不完整的情况）
> > > 2.9 加了个过滤器给过滤掉了
> > 
> > 
> > 2.8
> 
> 是 docker 部署吗？

2.8 Windows X64 Native Image

**Comment by Ghost-chu** [comment]
请稍等一会儿，我们晚些时候发布 2.10 版本

**Comment by Ghost-chu** [comment]
https://github.com/Ghost-chu/PeerBanHelper/releases/tag/v2.10

**Comment by Ghost-chu** [comment]
我先将此 Issue 关闭，如果您在更新到 v2.10 后仍然发现此类 Peer，请重新打开一个 Issue
