### ISSUE TITLE
[BUG][WebUI] 被封禁频率最高的前50个IP地址显示异常

### ISSUE THREAD

**Issue by rihalvnium76** [Ghost-chu/PeerBanHelper#57]
版本：PBH v2.10 win x64 Native Image

![image](https://github.com/Ghost-chu/PeerBanHelper/assets/57667144/3cacec41-1842-4b37-a047-13b09499dad0)

不管是页面显示，还是网络请求返回的数据，都明显不正常

**Comment by Ghost-chu** [comment]
一个已知问题，会在 v3 修复

**Comment by Ghost-chu** [comment]
看看 v3.1.1 修复了吗

**Comment by Sora39831** [comment]
> 看看 v3.1.1 修复了吗

修复了，已经正常显示了

**Comment by rihalvnium76** [comment]
似乎正常了
