### ISSUE TITLE
请问配置文件生成在什么位置？

### ISSUE THREAD

**Issue by LightmoonXD** [Ghost-chu/PeerBanHelper#7]
第一次接触Java...
平台是macOS。按照指南运行之后显示
WARNING: Runtime environment or build system does not support multi-release JARs. This will impact location-based features.
[02:27:48] [main/INFO]: PeerBanHelper - v1.5 - by Ghost_chu
[02:27:48] [main/INFO]: 加载配置文件……
[02:27:48] [main/WARN]: 请配置 config.yml 和 profile.yml 后，重新启动 PeerBanHelper。

不知道是否成功运行了。在Jar文件那层目录下没有找到。

**Comment by LightmoonXD** [comment]
解决了...macOS不能在终端下运行，应该直接在Finder中右键执行，否则没有权限在系统文件夹创建新文档。

**Comment by LightmoonXD** [comment]
另一个问题...配置文件好像没有生效？
![截屏2024-02-23 03 28 14](https://github.com/Ghost-chu/PeerBanHelper/assets/21337686/86ef86e3-b7ab-4406-86c5-777154c02c76)
![截屏2024-02-23 03 27 55](https://github.com/Ghost-chu/PeerBanHelper/assets/21337686/0b57740c-0d06-4cf8-9117-9b368380a2ca)

**Comment by Ghost-chu** [comment]
> ![截屏2024-02-23 03 29 43](https://private-user-images.githubusercontent.com/21337686/307125633-cfd46c97-b609-47a1-bda7-e95a336c15c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5MzcwMDksIm5iZiI6MTcwODkzNjcwOSwicGF0aCI6Ii8yMTMzNzY4Ni8zMDcxMjU2MzMtY2ZkNDZjOTctYjYwOS00N2ExLWJkYTctZTk1YTMzNmMxNWMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDA4MzgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3ZTBkMWUzNGQ2NDVkMGQ5MjA3MzQ0YmVjODRkODUyNzYyYjJhOGVjYWQ0MTc0MDY2ZTNhYzQ1YmZjMmEwZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oIdMGPS80-6BOoDF7kbB5PaXVGHM1LHy3rguVCTGPWg) 这是我的qb配置截图。 请问config中的server字段是什么意思？如果我在本地机器上运行是不是应该注释掉这段？

> server 只对 transmission 有效。

qBittorrent 的 IP 地址那个框要填 `*`

**Comment by LightmoonXD** [comment]
> > ![截屏2024-02-23 03 29 43](https://private-user-images.githubusercontent.com/21337686/307125633-cfd46c97-b609-47a1-bda7-e95a336c15c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5MzcwMDksIm5iZiI6MTcwODkzNjcwOSwicGF0aCI6Ii8yMTMzNzY4Ni8zMDcxMjU2MzMtY2ZkNDZjOTctYjYwOS00N2ExLWJkYTctZTk1YTMzNmMxNWMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDA4MzgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3ZTBkMWUzNGQ2NDVkMGQ5MjA3MzQ0YmVjODRkODUyNzYyYjJhOGVjYWQ0MTc0MDY2ZTNhYzQ1YmZjMmEwZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oIdMGPS80-6BOoDF7kbB5PaXVGHM1LHy3rguVCTGPWg) 这是我的qb配置截图。 请问config中的server字段是什么意思？如果我在本地机器上运行是不是应该注释掉这段？
> 
> > server 只对 transmission 有效。
> 
> qBittorrent 的 IP 地址那个框要填 `*`

好的，已成功了～谢谢
