### ISSUE TITLE
可疑的新客户端

### ISSUE THREAD

**Issue by LightmoonXD** [Ghost-chu/PeerBanHelper#8]
如图，这个客户端有多个可以连接，似乎可以正常下载完，不过流量非常大。
![截屏2024-03-02 11 07 57](https://github.com/Ghost-chu/PeerBanHelper/assets/21337686/0085e372-a566-4912-bf26-31f7115456c4)
还需要更多证据

**Comment by Ghost-chu** [comment]
已合并到新版本预设规则中
